application: hdevents-1209
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- deferred: on
- remote_api: on

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: hdeventsapi.application
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.app
  login: admin  
- url: /expire
  login: admin
  script: main.app
- url: /expiring
  login: admin
  script: main.app
- url: /cronbugowners
  login: admin
  script: main.app
- url: /test.*
  login: admin
  script: gaeunit.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.app
  login: admin
- url: /_km/.*
  script: keymaster.app
  login: admin
- url: .*
  script: main.app
  
libraries:
- name: django
  version: latest
- name: jinja2
  version: latest
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0

  
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
 